# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ogcex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import spapi_pb2 as spapi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bogcex.proto\x1a\x0bspapi.proto\"\x83\x01\n\x0b\x45pochOrders\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12(\n\x06orders\x18\x14 \x03(\x0b\x32\x18.EpochOrders.OrdersEntry\x1a;\n\x0bOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.Transaction:\x02\x38\x01\"\x9a\x01\n\x0bMarketQuote\x12\x0f\n\x07\x62idsize\x18\n \x01(\x05\x12\x0b\n\x03\x62id\x18\x14 \x01(\x05\x12\x0b\n\x03\x61sk\x18\x1e \x01(\x05\x12\x0f\n\x07\x61sksize\x18( \x01(\x05\x12\x0c\n\x04last\x18\x32 \x01(\x05\x12\x10\n\x08lastsize\x18< \x01(\x05\x12\x10\n\x08upordown\x18\x46 \x01(\x08\x12\x0e\n\x06symbol\x18P \x01(\t\x12\r\n\x05\x65poch\x18Z \x01(\x04\"q\n\x08\x45pochBar\x12\x0e\n\x06symbol\x18\n \x01(\t\x12\r\n\x05\x65poch\x18\x0f \x01(\x04\x12\x0c\n\x04open\x18\x14 \x01(\x05\x12\x0c\n\x04high\x18\x1e \x01(\x05\x12\x0b\n\x03low\x18( \x01(\x05\x12\r\n\x05\x63lose\x18\x32 \x01(\x05\x12\x0e\n\x06volume\x18< \x01(\x05\"\xc3\x01\n\tBookOrder\x12\x0c\n\x04side\x18\n \x01(\x08\x12\r\n\x05price\x18\x14 \x01(\x05\x12\x10\n\x08open_qty\x18\x1e \x01(\x05\x12\x12\n\nfilled_qty\x18( \x01(\x05\x12\x15\n\rremaining_qty\x18\x32 \x01(\x05\x12\x14\n\x0c\x63\x61nceled_qty\x18< \x01(\x05\x12\x0e\n\x06symbol\x18\x46 \x01(\t\x12\x13\n\x0bupdate_time\x18P \x01(\t\x12\x0f\n\x07orderid\x18Z \x01(\t\x12\x10\n\x08traderid\x18\x64 \x01(\t\"H\n\tDepthItem\x12\r\n\x05level\x18\n \x01(\x05\x12\t\n\x01\x62\x18\x1e \x01(\x05\x12\t\n\x01\x61\x18( \x01(\x05\x12\n\n\x02\x62s\x18\x32 \x01(\x05\x12\n\n\x02\x61s\x18< \x01(\x05\"|\n\nMarketData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\x16\n\x03\x62\x61r\x18\x14 \x01(\x0b\x32\t.EpochBar\x12\x1b\n\x05quote\x18\x1e \x01(\x0b\x32\x0c.MarketQuote\x12\x19\n\x05\x64\x65pth\x18( \x03(\x0b\x32\n.DepthItemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ogcex_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EPOCHORDERS_ORDERSENTRY._options = None
  _EPOCHORDERS_ORDERSENTRY._serialized_options = b'8\001'
  _EPOCHORDERS._serialized_start=29
  _EPOCHORDERS._serialized_end=160
  _EPOCHORDERS_ORDERSENTRY._serialized_start=101
  _EPOCHORDERS_ORDERSENTRY._serialized_end=160
  _MARKETQUOTE._serialized_start=163
  _MARKETQUOTE._serialized_end=317
  _EPOCHBAR._serialized_start=319
  _EPOCHBAR._serialized_end=432
  _BOOKORDER._serialized_start=435
  _BOOKORDER._serialized_end=630
  _DEPTHITEM._serialized_start=632
  _DEPTHITEM._serialized_end=704
  _MARKETDATA._serialized_start=706
  _MARKETDATA._serialized_end=830
# @@protoc_insertion_point(module_scope)
