# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bspapi.proto\"\xb4\x01\n\x0bTransaction\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\n \x01(\x04\x12\x1e\n\tnew_order\x18\x14 \x01(\x0b\x32\t.NewOrderH\x00\x12\x18\n\x0e\x63\x61ncel_orderid\x18\x1e \x01(\tH\x00\x12\"\n\x0b\x61uction_bid\x18( \x01(\x0b\x32\x0b.AuctionBidH\x00\x12\n\n\x02id\x18\x64 \x01(\x0c\x12\x11\n\tsignature\x18n \x01(\x0c\x42\x04\n\x02tx\"E\n\x08NewOrder\x12\x0c\n\x04side\x18\n \x01(\x08\x12\x0c\n\x04size\x18\x14 \x01(\x05\x12\r\n\x05price\x18\x1e \x01(\x05\x12\x0e\n\x06symbol\x18( \x01(\t\"M\n\nAuctionBid\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\x0c\n\x04hash\x18\x14 \x01(\t\x12\x15\n\rordering_salt\x18\x1e \x01(\t\x12\x0b\n\x03\x62id\x18( \x01(\x05\"H\n\nEpochEvent\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\x0c\n\x04hash\x18\x14 \x01(\t\x12\n\n\x02id\x18\x64 \x01(\x0c\x12\x11\n\tsignature\x18n \x01(\x0c\"i\n\rTxBlockStream\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\"\n\x0b\x65poch_event\x18\x14 \x01(\x0b\x32\x0b.EpochEventH\x00\x12\x1a\n\x02tx\x18\x1e \x01(\x0b\x32\x0c.TransactionH\x00\x42\t\n\x07txepochb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTION._serialized_start=16
  _TRANSACTION._serialized_end=196
  _NEWORDER._serialized_start=198
  _NEWORDER._serialized_end=267
  _AUCTIONBID._serialized_start=269
  _AUCTIONBID._serialized_end=346
  _EPOCHEVENT._serialized_start=348
  _EPOCHEVENT._serialized_end=420
  _TXBLOCKSTREAM._serialized_start=422
  _TXBLOCKSTREAM._serialized_end=527
# @@protoc_insertion_point(module_scope)
