# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spapi.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bspapi.proto\"\xb4\x01\n\x0bTransaction\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\n \x01(\x04\x12\x1e\n\tnew_order\x18\x14 \x01(\x0b\x32\t.NewOrderH\x00\x12\x18\n\x0e\x63\x61ncel_orderid\x18\x1e \x01(\tH\x00\x12\"\n\x0b\x61uction_bid\x18( \x01(\x0b\x32\x0b.AuctionBidH\x00\x12\n\n\x02id\x18\x64 \x01(\t\x12\x11\n\tsignature\x18n \x01(\x0c\x42\x04\n\x02tx\"E\n\x08NewOrder\x12\x0c\n\x04side\x18\n \x01(\x08\x12\x0c\n\x04size\x18\x14 \x01(\x05\x12\r\n\x05price\x18\x1e \x01(\x05\x12\x0e\n\x06symbol\x18( \x01(\t\"M\n\nAuctionBid\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\x0c\n\x04hash\x18\x14 \x01(\t\x12\x15\n\rordering_salt\x18\x1e \x01(\t\x12\x0b\n\x03\x62id\x18( \x01(\x05\"H\n\nEpochEvent\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\x0c\n\x04hash\x18\x14 \x01(\t\x12\n\n\x02id\x18\x64 \x01(\t\x12\x11\n\tsignature\x18n \x01(\x0c\"i\n\rTxBlockStream\x12\r\n\x05\x65poch\x18\n \x01(\x04\x12\"\n\x0b\x65poch_event\x18\x14 \x01(\x0b\x32\x0b.EpochEventH\x00\x12\x1a\n\x02tx\x18\x1e \x01(\x0b\x32\x0c.TransactionH\x00\x42\t\n\x07txepochb\x06proto3')
)




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Transaction.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Transaction.timestamp', index=1,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_order', full_name='Transaction.new_order', index=2,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancel_orderid', full_name='Transaction.cancel_orderid', index=3,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auction_bid', full_name='Transaction.auction_bid', index=4,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Transaction.id', index=5,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Transaction.signature', index=6,
      number=110, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tx', full_name='Transaction.tx',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=16,
  serialized_end=196,
)


_NEWORDER = _descriptor.Descriptor(
  name='NewOrder',
  full_name='NewOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='NewOrder.side', index=0,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='NewOrder.size', index=1,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='NewOrder.price', index=2,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='NewOrder.symbol', index=3,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=267,
)


_AUCTIONBID = _descriptor.Descriptor(
  name='AuctionBid',
  full_name='AuctionBid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='AuctionBid.epoch', index=0,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='AuctionBid.hash', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ordering_salt', full_name='AuctionBid.ordering_salt', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid', full_name='AuctionBid.bid', index=3,
      number=40, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=346,
)


_EPOCHEVENT = _descriptor.Descriptor(
  name='EpochEvent',
  full_name='EpochEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='EpochEvent.epoch', index=0,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='EpochEvent.hash', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='EpochEvent.id', index=2,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='EpochEvent.signature', index=3,
      number=110, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=420,
)


_TXBLOCKSTREAM = _descriptor.Descriptor(
  name='TxBlockStream',
  full_name='TxBlockStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='TxBlockStream.epoch', index=0,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_event', full_name='TxBlockStream.epoch_event', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx', full_name='TxBlockStream.tx', index=2,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='txepoch', full_name='TxBlockStream.txepoch',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=422,
  serialized_end=527,
)

_TRANSACTION.fields_by_name['new_order'].message_type = _NEWORDER
_TRANSACTION.fields_by_name['auction_bid'].message_type = _AUCTIONBID
_TRANSACTION.oneofs_by_name['tx'].fields.append(
  _TRANSACTION.fields_by_name['new_order'])
_TRANSACTION.fields_by_name['new_order'].containing_oneof = _TRANSACTION.oneofs_by_name['tx']
_TRANSACTION.oneofs_by_name['tx'].fields.append(
  _TRANSACTION.fields_by_name['cancel_orderid'])
_TRANSACTION.fields_by_name['cancel_orderid'].containing_oneof = _TRANSACTION.oneofs_by_name['tx']
_TRANSACTION.oneofs_by_name['tx'].fields.append(
  _TRANSACTION.fields_by_name['auction_bid'])
_TRANSACTION.fields_by_name['auction_bid'].containing_oneof = _TRANSACTION.oneofs_by_name['tx']
_TXBLOCKSTREAM.fields_by_name['epoch_event'].message_type = _EPOCHEVENT
_TXBLOCKSTREAM.fields_by_name['tx'].message_type = _TRANSACTION
_TXBLOCKSTREAM.oneofs_by_name['txepoch'].fields.append(
  _TXBLOCKSTREAM.fields_by_name['epoch_event'])
_TXBLOCKSTREAM.fields_by_name['epoch_event'].containing_oneof = _TXBLOCKSTREAM.oneofs_by_name['txepoch']
_TXBLOCKSTREAM.oneofs_by_name['txepoch'].fields.append(
  _TXBLOCKSTREAM.fields_by_name['tx'])
_TXBLOCKSTREAM.fields_by_name['tx'].containing_oneof = _TXBLOCKSTREAM.oneofs_by_name['txepoch']
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['NewOrder'] = _NEWORDER
DESCRIPTOR.message_types_by_name['AuctionBid'] = _AUCTIONBID
DESCRIPTOR.message_types_by_name['EpochEvent'] = _EPOCHEVENT
DESCRIPTOR.message_types_by_name['TxBlockStream'] = _TXBLOCKSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'spapi_pb2'
  # @@protoc_insertion_point(class_scope:Transaction)
  ))
_sym_db.RegisterMessage(Transaction)

NewOrder = _reflection.GeneratedProtocolMessageType('NewOrder', (_message.Message,), dict(
  DESCRIPTOR = _NEWORDER,
  __module__ = 'spapi_pb2'
  # @@protoc_insertion_point(class_scope:NewOrder)
  ))
_sym_db.RegisterMessage(NewOrder)

AuctionBid = _reflection.GeneratedProtocolMessageType('AuctionBid', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONBID,
  __module__ = 'spapi_pb2'
  # @@protoc_insertion_point(class_scope:AuctionBid)
  ))
_sym_db.RegisterMessage(AuctionBid)

EpochEvent = _reflection.GeneratedProtocolMessageType('EpochEvent', (_message.Message,), dict(
  DESCRIPTOR = _EPOCHEVENT,
  __module__ = 'spapi_pb2'
  # @@protoc_insertion_point(class_scope:EpochEvent)
  ))
_sym_db.RegisterMessage(EpochEvent)

TxBlockStream = _reflection.GeneratedProtocolMessageType('TxBlockStream', (_message.Message,), dict(
  DESCRIPTOR = _TXBLOCKSTREAM,
  __module__ = 'spapi_pb2'
  # @@protoc_insertion_point(class_scope:TxBlockStream)
  ))
_sym_db.RegisterMessage(TxBlockStream)


# @@protoc_insertion_point(module_scope)
