// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    publicGetStatus (params?: {}): Promise<implicitReturnType>;
    publicGetMarkets (params?: {}): Promise<implicitReturnType>;
    publicGetNonce (params?: {}): Promise<implicitReturnType>;
    publicGetTickerSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetOrderbookSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetTradesSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetOhlcvSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetBalanceAddress (params?: {}): Promise<implicitReturnType>;
    publicGetPositionsAddress (params?: {}): Promise<implicitReturnType>;
    publicGetOpenOrdersAddress (params?: {}): Promise<implicitReturnType>;
    publicGetOrdersOrderid (params?: {}): Promise<implicitReturnType>;
    publicGetMyTradesAddress (params?: {}): Promise<implicitReturnType>;
    publicGetRejectionsAddress (params?: {}): Promise<implicitReturnType>;
    publicPostRelay (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
